export enum Campo {
  NOMBRE_CLIENTE = 'NOMBRE_CLIENTE',
  IDENT_LEGAL = 'IDENT_LEGAL',
  UNIDAD_NEGOCIO = 'UNIDAD_NEGOCIO',
  COD_LOCAL = 'COD_LOCAL',
  NOMBRE_LOCAL = 'NOMBRE_LOCAL',
  CANTIDAD = 'CANTIDAD',
  COD_CENCOSUD = 'COD_CENCOSUD',
  COD_PRODUCTO = 'COD_PRODUCTO',
  NUM_ORDEN = 'NUM_ORDEN',
  FEC_EMISION = 'FEC_EMISION',
  FEC_ENTREGA = 'FEC_ENTREGA',
}
